### ISSUE TITLE
go version on release not correct 

### ISSUE THREAD

**Issue by vfonsecapv** [cloudfoundry-incubator/notifications-release#10]
Staging...
-------> Buildpack version 1.7.5
file:///tmp/buildpacks/fa21214ae1628b6399e76c2a9cc2da08/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_godep_godep-v62-linux-x64.tgz
-----> Checking Godeps/Godeps.json file.
DEPENDENCY MISSING IN MANIFEST: go 1.5.2
It looks like you're trying to use go 1.5.2.
Unfortunately, that version of go is not supported by this buildpack.
The versions of go supported in this buildpack are:
- 1.6.1
- 1.6
- 1.5.4
- 1.5.3
- 1.4.3
- 1.4.2

**Comment by dprotaso** [comment]
This was done a while back
https://github.com/cloudfoundry-incubator/notifications-release/commit/f4518d216f346d95f858a5a3b7a294bb1cb9f4f2
