### ISSUE TITLE
Can this release use a MySQL service broker in a spinning Cloud Foundry?

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-incubator/notifications-release#12]
We are already running a MySQL database service, which is available through our CF marketplace.  Is there a way to tell the notifications application (when deployed via CF) to provision a service instance and use that, instead of manually defining a database URL?

**Comment by dprotaso** [comment]
Some deployments don't use a mysql database that's provided by a broker so I'd rather not make the release opinionated.
